version: '3'
services:
  app:
    build: ../app
    command: npm run dev
    volumes:
      - ../app/:/app/
      - /app/node_modules/
    ports:
      - 3000:3000
  wordpress:
    image: visiblevc/wordpress:0.17.0-php7.1
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ../wp/data:/data
      - ../wp/wp-content/themes/block-by-bit:/app/wp-content/themes/block-by-bit
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        academic-bloggers-toolkit,
        co-authors-plus,
        [WP-API]https://github.com/WP-API/WP-API/archive/master.zip,
  db:
    image: mysql:5.7
    volumes:
      - ../wp/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
  app: